micronaut:
  application:
    name: mn-transactions-issues

datasources:
  default:
    url: "jdbc:tc:postgresql:11.5:///testdb"
    username: 'sa'
    password: 'as'
    driverClassName: 'org.testcontainers.jdbc.ContainerDatabaseDriver'
    transaction-isolation: "TRANSACTION_READ_COMMITTED"

flyway:
  datasources:
    default:
      locations: classpath:db.migrations, classpath:db.testdata #include test data for test!
jpa:
  default:
    entity-scan:
      packages: 'mn.transactions.issues'
